-- Agrilink database schema.
--
-- Run this whole file in the Supabase SQL Editor. It is idempotent: it works on a
-- fresh project AND upgrades the original v1 schema in place (existing rows are kept).
--
-- Security model: every table has Row Level Security enabled with NO policies, so the
-- public anon key (which ships in browsers) can read/write nothing. Only the Express
-- backend, using the service_role key, touches the database - after verifying the
-- caller's Firebase ID token and checking ownership.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public."Category" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    "imageUrl" TEXT,
    "productCount" INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

insert into public."Category" (id, name, description, "imageUrl", "productCount")
values
  (1, 'Vegetables', 'Fresh vegetables from local farms', '/images/categories/vegetables.jpg', 0),
  (2, 'Fruits', 'Seasonal and exotic fruits', '/images/categories/fruits.jpg', 0),
  (3, 'Dairy', 'Fresh milk, cheese, and other dairy products', '/images/categories/dairy.jpg', 0),
  (4, 'Grains', 'Whole grains and cereals', '/images/categories/grains.jpg', 0),
  (5, 'Meat', 'Farm-raised meats', '/images/categories/meat.jpg', 0),
  (6, 'Honey', 'Pure and raw honey varieties', '/images/categories/honey.jpg', 0),
  (7, 'Eggs', 'Farm-fresh eggs', '/images/categories/eggs.jpg', 0),
  (8, 'Herbs', 'Fresh and dried herbs', '/images/categories/herbs.jpg', 0),
  (9, 'Nuts', 'Variety of nuts and seeds', '/images/categories/nuts.jpg', 0),
  (10, 'Oils', 'Cold-pressed and natural oils', '/images/categories/oils.jpg', 0)
on conflict (id) do nothing;

-- Explicit ids above do not advance the identity sequence; fix it so inserts don't collide.
select setval(pg_get_serial_sequence('public."Category"', 'id'), (select max(id) from public."Category"));

-- Seller / buyer identity is the Firebase UID (a string), never a client-chosen number.
create table if not exists public."Profile" (
    uid TEXT PRIMARY KEY,
    email TEXT,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Buyer', 'Farmer')),
    "contactNumber" TEXT,
    address TEXT,
    terrain TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

create table if not exists public."Product" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    "categoryId" INTEGER REFERENCES public."Category"(id),
    "categoryName" TEXT,
    price NUMERIC NOT NULL,
    "quantityAvailable" INTEGER NOT NULL,
    "sellerId" TEXT,
    "sellerName" TEXT,
    "productionType" TEXT,
    "imageUrl" TEXT,
    "farmerId" TEXT,       -- legacy duplicate of sellerId, no longer written
    "farmerName" TEXT,     -- legacy duplicate of sellerName, no longer written
    category TEXT,         -- legacy duplicate of categoryName, no longer written
    rating NUMERIC DEFAULT 0,
    reviews INTEGER DEFAULT 0,
    "inStock" BOOLEAN DEFAULT true,
    unit TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

create table if not exists public."Order" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "buyerId" TEXT,
    "buyerName" TEXT,
    "totalAmount" NUMERIC NOT NULL,
    status TEXT DEFAULT 'Pending',  -- legacy; the effective status is derived from OrderItem.status
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- One row per product line. Status lives here because one order can span several farmers,
-- and each farmer fulfils (and may cancel) only their own lines.
create table if not exists public."OrderItem" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "orderId" BIGINT NOT NULL REFERENCES public."Order"(id) ON DELETE CASCADE,
    "productId" BIGINT REFERENCES public."Product"(id) ON DELETE SET NULL,
    "productName" TEXT NOT NULL,       -- snapshots, so history survives product edits/deletes
    unit TEXT,
    "unitPrice" NUMERIC NOT NULL CHECK ("unitPrice" >= 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    "sellerId" TEXT NOT NULL,
    "sellerName" TEXT,
    status TEXT NOT NULL DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Messages from the public contact form. Read them in the Supabase dashboard (Table editor).
create table if not exists public."ContactMessage" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ---------------------------------------------------------------------------
-- Upgrade path from the v1 schema (all no-ops on a fresh database)
-- ---------------------------------------------------------------------------

alter table public."Product" alter column "sellerId" type text using "sellerId"::text;
alter table public."Product" alter column "farmerId" type text using "farmerId"::text;
alter table public."Order" alter column "buyerId" type text using "buyerId"::text;
alter table public."Order" add column if not exists "shippingAmount" NUMERIC NOT NULL DEFAULT 0;
-- Delivery details are snapshotted onto the order so sellers can fulfil it even if the buyer edits their profile later.
alter table public."Order" add column if not exists "shippingAddress" TEXT;
alter table public."Order" add column if not exists "contactNumber" TEXT;

alter table public."Order" drop constraint if exists "Order_status_check";

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'product_price_nonneg') then
    alter table public."Product" add constraint product_price_nonneg check (price >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'product_qty_nonneg') then
    alter table public."Product" add constraint product_qty_nonneg check ("quantityAvailable" >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'orderitem_status_valid') then
    alter table public."OrderItem" add constraint orderitem_status_valid
      check (status in ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled'));
  end if;
end $$;

create index if not exists product_seller_idx on public."Product" ("sellerId");
create index if not exists product_category_idx on public."Product" ("categoryId");
create index if not exists order_buyer_idx on public."Order" ("buyerId");
create index if not exists orderitem_order_idx on public."OrderItem" ("orderId");
create index if not exists orderitem_seller_idx on public."OrderItem" ("sellerId");

-- ---------------------------------------------------------------------------
-- Row Level Security: lock the tables to the anon/authenticated keys entirely.
-- ---------------------------------------------------------------------------

alter table public."Category" enable row level security;
alter table public."Profile" enable row level security;
alter table public."Product" enable row level security;
alter table public."Order" enable row level security;
alter table public."OrderItem" enable row level security;
alter table public."ContactMessage" enable row level security;


-- ---------------------------------------------------------------------------
-- v3 additions: payments (cash on delivery), per-farmer shipping, reviews, notifications, storage
-- ---------------------------------------------------------------------------

-- Payment is cash on delivery for now. The column exists so a gateway can be added later
-- without reshaping orders; a COD order counts as paid once all its live lines are Delivered.
alter table public."Order" add column if not exists "paymentMethod" TEXT NOT NULL DEFAULT 'COD';

-- One review per purchased line, and only after delivery (enforced in submit_review).
create table if not exists public."Review" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "productId" BIGINT NOT NULL REFERENCES public."Product"(id) ON DELETE CASCADE,
    "orderItemId" BIGINT NOT NULL UNIQUE REFERENCES public."OrderItem"(id) ON DELETE CASCADE,
    "reviewerId" TEXT NOT NULL,
    "reviewerName" TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT NOT NULL DEFAULT '' CHECK (char_length(comment) <= 1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
create index if not exists review_product_idx on public."Review" ("productId", created_at desc);
create index if not exists review_reviewer_idx on public."Review" ("reviewerId");

create table if not exists public."Notification" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" TEXT NOT NULL,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT,
    link TEXT,
    read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
create index if not exists notification_user_idx on public."Notification" ("userId", created_at desc);

alter table public."Review" enable row level security;
alter table public."Notification" enable row level security;

-- Product images: a public-read bucket. Uploads only happen through short-lived signed URLs minted by the
-- API (service role), so no client-side insert policy exists. Skipped on plain Postgres without Supabase Storage.
do $$
begin
  if exists (select 1 from information_schema.schemata where schema_name = 'storage') then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values ('product-images', 'product-images', true, 3145728, array['image/jpeg', 'image/png', 'image/webp'])
    on conflict (id) do update
      set public = true, file_size_limit = 3145728, allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp'];
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- place_order: the ONLY way an order is created. One transaction, so stock can never go negative,
-- two buyers can't both take the last unit, and an order is never saved without its lines.
-- Prices come from the Product table, never the client. Shipping is charged once per farmer.
-- Each farmer gets a notification.
-- ---------------------------------------------------------------------------

drop function if exists public.place_order(text, text, numeric, text, text, jsonb);

create or replace function public.place_order(
    p_buyer_id text,
    p_buyer_name text,
    p_shipping_per_seller numeric,
    p_address text,
    p_phone text,
    p_items jsonb
) returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_order_id bigint;
    v_total numeric := 0;
    v_line record;
    v_prod record;
    v_seller record;
    v_sellers int;
begin
    if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
        raise exception 'empty_order';
    end if;

    insert into "Order" ("buyerId", "buyerName", "totalAmount", "shippingAmount", "shippingAddress", "contactNumber", status, "paymentMethod")
    values (p_buyer_id, p_buyer_name, 0, 0, p_address, p_phone, 'Pending', 'COD')
    returning id into v_order_id;

    -- Lines are merged per product and processed in id order so concurrent orders lock rows in the
    -- same order (no deadlocks).
    for v_line in
        select (e ->> 'productId')::bigint as product_id, sum((e ->> 'quantity')::int)::int as qty
        from jsonb_array_elements(p_items) e
        group by 1
        order by 1
    loop
        update "Product"
           set "quantityAvailable" = "quantityAvailable" - v_line.qty,
               "inStock" = ("quantityAvailable" - v_line.qty) > 0
         where id = v_line.product_id
           and "quantityAvailable" >= v_line.qty
           and "sellerId" is not null
        returning * into v_prod;

        if not found then
            raise exception 'insufficient_stock:%', v_line.product_id;
        end if;

        if v_prod."sellerId" = p_buyer_id then
            raise exception 'own_product:%', v_line.product_id;
        end if;

        insert into "OrderItem" ("orderId", "productId", "productName", unit, "unitPrice", quantity, "sellerId", "sellerName", status)
        values (v_order_id, v_prod.id, v_prod.name, v_prod.unit, v_prod.price, v_line.qty, v_prod."sellerId", v_prod."sellerName", 'Pending');

        v_total := v_total + v_prod.price * v_line.qty;
    end loop;

    select count(distinct "sellerId") into v_sellers from "OrderItem" where "orderId" = v_order_id;
    v_total := v_total + p_shipping_per_seller * v_sellers;
    update "Order" set "totalAmount" = v_total, "shippingAmount" = p_shipping_per_seller * v_sellers where id = v_order_id;

    for v_seller in
        select "sellerId", count(*)::int as n from "OrderItem" where "orderId" = v_order_id group by "sellerId"
    loop
        insert into "Notification" ("userId", type, title, body, link)
        values (v_seller."sellerId", 'order_placed', 'New order #' || v_order_id,
                p_buyer_name || ' ordered ' || v_seller.n || (case when v_seller.n = 1 then ' item' else ' items' end) || ' from you.',
                '/order/' || v_order_id);
    end loop;

    return v_order_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- update_order_item_status: enforces who may move a line to which status, returns stock on cancel
-- (row-locked so two requests can't both restock) and notifies the other party.
--   seller: Pending -> Processing | Cancelled, Processing -> Shipped | Cancelled, Shipped -> Delivered
--   buyer : Pending -> Cancelled
-- ---------------------------------------------------------------------------

create or replace function public.update_order_item_status(
    p_item_id bigint,
    p_actor_id text,
    p_new_status text
) returns "OrderItem"
language plpgsql
security definer
set search_path = public
as $$
declare
    v_item "OrderItem";
    v_buyer text;
    v_is_seller boolean;
    v_is_buyer boolean;
    v_ok boolean := false;
begin
    select * into v_item from "OrderItem" where id = p_item_id for update;
    if not found then
        raise exception 'not_found';
    end if;

    select "buyerId" into v_buyer from "Order" where id = v_item."orderId";
    v_is_seller := v_item."sellerId" = p_actor_id;
    v_is_buyer := v_buyer = p_actor_id;

    if not (v_is_seller or v_is_buyer) then
        raise exception 'not_found';   -- don't reveal that the line exists
    end if;

    if v_is_seller then
        v_ok := (v_item.status, p_new_status) in
            (('Pending', 'Processing'), ('Pending', 'Cancelled'),
             ('Processing', 'Shipped'), ('Processing', 'Cancelled'),
             ('Shipped', 'Delivered'));
    end if;
    if not v_ok and v_is_buyer then
        v_ok := v_item.status = 'Pending' and p_new_status = 'Cancelled';
    end if;

    if not v_ok then
        raise exception 'invalid_transition:%->%', v_item.status, p_new_status;
    end if;

    if p_new_status = 'Cancelled' and v_item."productId" is not null then
        update "Product"
           set "quantityAvailable" = "quantityAvailable" + v_item.quantity,
               "inStock" = true
         where id = v_item."productId";
    end if;

    update "OrderItem" set status = p_new_status where id = p_item_id returning * into v_item;

    if v_is_seller and not v_is_buyer then
        insert into "Notification" ("userId", type, title, body, link)
        values (v_buyer, 'order_status', 'Order #' || v_item."orderId" || ' update',
                v_item."productName" || ' is now ' || lower(p_new_status) || '.', '/order/' || v_item."orderId");
    elsif v_is_buyer and not v_is_seller then
        insert into "Notification" ("userId", type, title, body, link)
        values (v_item."sellerId", 'order_status', 'Order #' || v_item."orderId" || ' update',
                'The buyer cancelled ' || v_item."productName" || '.', '/order/' || v_item."orderId");
    end if;

    return v_item;
end;
$$;

-- ---------------------------------------------------------------------------
-- Reviews. submit_review only accepts a review from the buyer of a Delivered line, once per line,
-- and keeps Product.rating / Product.reviews in sync inside the same transaction.
-- ---------------------------------------------------------------------------

create or replace function public.refresh_product_rating(p_product_id bigint) returns void
language sql
security definer
set search_path = public
as $$
    update "Product" p
       set rating = coalesce((select round(avg(rating)::numeric, 2) from "Review" where "productId" = p_product_id), 0),
           reviews = (select count(*) from "Review" where "productId" = p_product_id)
     where p.id = p_product_id;
$$;

create or replace function public.submit_review(
    p_item_id bigint,
    p_buyer_id text,
    p_buyer_name text,
    p_rating int,
    p_comment text
) returns "Review"
language plpgsql
security definer
set search_path = public
as $$
declare
    v_item "OrderItem";
    v_buyer text;
    v_review "Review";
    v_seller_name text;
begin
    if p_rating is null or p_rating < 1 or p_rating > 5 then
        raise exception 'invalid_rating';
    end if;

    select * into v_item from "OrderItem" where id = p_item_id;
    if not found then
        raise exception 'not_found';
    end if;
    select "buyerId" into v_buyer from "Order" where id = v_item."orderId";
    if v_buyer is distinct from p_buyer_id then
        raise exception 'not_found';
    end if;
    if v_item.status <> 'Delivered' then
        raise exception 'not_delivered';
    end if;
    if v_item."productId" is null then
        raise exception 'product_gone';
    end if;
    if exists (select 1 from "Review" where "orderItemId" = p_item_id) then
        raise exception 'already_reviewed';
    end if;

    -- Serialise reviewers of the same product. Without this lock, two simultaneous reviews would each compute the
    -- average without seeing the other's uncommitted row and leave Product.rating / reviews permanently stale.
    perform 1 from "Product" where id = v_item."productId" for update;

    insert into "Review" ("productId", "orderItemId", "reviewerId", "reviewerName", rating, comment)
    values (v_item."productId", p_item_id, p_buyer_id, p_buyer_name, p_rating, coalesce(btrim(p_comment), ''))
    returning * into v_review;

    perform refresh_product_rating(v_item."productId");

    insert into "Notification" ("userId", type, title, body, link)
    values (v_item."sellerId", 'review', 'New ' || p_rating || '-star review',
            p_buyer_name || ' reviewed ' || v_item."productName" || '.', '/product/' || v_item."productId");

    return v_review;
end;
$$;

create or replace function public.delete_review(p_review_id bigint, p_buyer_id text) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_product bigint;
begin
    select "productId" into v_product from "Review" where id = p_review_id and "reviewerId" = p_buyer_id;
    if not found then
        raise exception 'not_found';
    end if;
    -- Same product-level lock as submit_review so the recomputed aggregate always includes every committed review.
    perform 1 from "Product" where id = v_product for update;
    delete from "Review" where id = p_review_id and "reviewerId" = p_buyer_id;
    if not found then
        raise exception 'not_found';   -- deleted by a concurrent request in the meantime
    end if;
    perform refresh_product_rating(v_product);
end;
$$;

-- ---------------------------------------------------------------------------
-- Aggregates done in SQL. Doing these in Node would mean pulling rows through PostgREST, which silently caps
-- responses at 1000 rows, so counts and totals would become wrong as the marketplace grows.
-- ---------------------------------------------------------------------------

-- In-stock product count per category (used on the home and category pages).
create or replace function public.category_counts()
returns table ("categoryId" int, n int)
language sql
stable
security definer
set search_path = public
as $$
    select "categoryId", count(*)::int from "Product" where "quantityAvailable" > 0 and "categoryId" is not null group by "categoryId";
$$;

-- Delivered, not-yet-reviewed lines of one product that this buyer received (what they may review now).
create or replace function public.eligible_review_items(p_buyer_id text, p_product_id bigint)
returns table ("orderItemId" bigint, "orderId" bigint)
language sql
stable
security definer
set search_path = public
as $$
    select i.id, i."orderId"
      from "OrderItem" i
      join "Order" o on o.id = i."orderId"
     where o."buyerId" = p_buyer_id
       and i."productId" = p_product_id
       and i.status = 'Delivered'
       and not exists (select 1 from "Review" r where r."orderItemId" = i.id)
     order by i.id;
$$;

-- Dashboard numbers over ALL of a user's orders (not just the first page).
--   Farmer: orders, openItems (Pending/Processing/Shipped lines), revenue (Delivered lines), months (last 6, UTC, non-cancelled)
--   Buyer : orders, inProgress (any live line still open), delivered (all live lines delivered), spent (live lines + shipping)
create or replace function public.order_stats(p_user_id text, p_role text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
    v jsonb;
begin
    if p_role = 'Farmer' then
        select jsonb_build_object(
                   'orders', count(distinct "orderId"),
                   'openItems', count(*) filter (where status in ('Pending', 'Processing', 'Shipped')),
                   'revenue', coalesce(sum("unitPrice" * quantity) filter (where status = 'Delivered'), 0))
          into v
          from "OrderItem" where "sellerId" = p_user_id;

        v := v || jsonb_build_object('months', coalesce((
            select jsonb_agg(jsonb_build_object('month', m, 'sales', s) order by m)
              from (select to_char(date_trunc('month', created_at at time zone 'utc'), 'YYYY-MM') as m,
                           sum("unitPrice" * quantity) as s
                      from "OrderItem"
                     where "sellerId" = p_user_id
                       and status <> 'Cancelled'
                       and (created_at at time zone 'utc') >= date_trunc('month', now() at time zone 'utc') - interval '5 months'
                     group by 1) t), '[]'::jsonb));
    else
        select jsonb_build_object(
                   'orders', count(*),
                   'inProgress', count(*) filter (where open_n > 0),
                   'delivered', count(*) filter (where live_n > 0 and open_n = 0),
                   'spent', coalesce(sum(case when live_n > 0 then live_sum + shipping else 0 end), 0))
          into v
          from (select o.id,
                       o."shippingAmount" as shipping,
                       count(*) filter (where i.status <> 'Cancelled') as live_n,
                       count(*) filter (where i.status in ('Pending', 'Processing', 'Shipped')) as open_n,
                       coalesce(sum(i."unitPrice" * i.quantity) filter (where i.status <> 'Cancelled'), 0) as live_sum
                  from "Order" o
                  join "OrderItem" i on i."orderId" = o.id
                 where o."buyerId" = p_user_id
                 group by o.id) t;
    end if;
    return v;
end;
$$;

-- ---------------------------------------------------------------------------
-- Only the service role may call these.
-- ---------------------------------------------------------------------------

revoke all on function public.place_order(text, text, numeric, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.update_order_item_status(bigint, text, text) from public, anon, authenticated;
revoke all on function public.refresh_product_rating(bigint) from public, anon, authenticated;
revoke all on function public.submit_review(bigint, text, text, int, text) from public, anon, authenticated;
revoke all on function public.delete_review(bigint, text) from public, anon, authenticated;
revoke all on function public.category_counts() from public, anon, authenticated;
revoke all on function public.eligible_review_items(text, bigint) from public, anon, authenticated;
revoke all on function public.order_stats(text, text) from public, anon, authenticated;
grant execute on function public.place_order(text, text, numeric, text, text, jsonb) to service_role;
grant execute on function public.update_order_item_status(bigint, text, text) to service_role;
grant execute on function public.refresh_product_rating(bigint) to service_role;
grant execute on function public.submit_review(bigint, text, text, int, text) to service_role;
grant execute on function public.delete_review(bigint, text) to service_role;
grant execute on function public.category_counts() to service_role;
grant execute on function public.eligible_review_items(text, bigint) to service_role;
grant execute on function public.order_stats(text, text) to service_role;
