-- Run this script in your Supabase SQL Editor to set up the Marketplace database

-- 1. Create Categories Table
CREATE TABLE IF NOT EXISTS public."Category" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    "imageUrl" TEXT,
    "productCount" INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert starting/mock categories so the frontend works immediately
INSERT INTO public."Category" (id, name, description, "imageUrl", "productCount")
VALUES 
  (1, 'Vegetables', 'Fresh vegetables from local farms', '/images/categories/vegetables.jpg', 15),
  (2, 'Fruits', 'Seasonal and exotic fruits', '/images/categories/fruits.jpg', 12),
  (3, 'Dairy', 'Fresh milk, cheese, and other dairy products', '/images/categories/dairy.jpg', 8),
  (4, 'Grains', 'Whole grains and cereals', '/images/categories/grains.jpg', 10),
  (5, 'Meat', 'Farm-raised meats', '/images/categories/meat.jpg', 6),
  (6, 'Honey', 'Pure and raw honey varieties', '/images/categories/honey.jpg', 4),
  (7, 'Eggs', 'Farm-fresh eggs', '/images/categories/eggs.jpg', 3)
ON CONFLICT (id) DO NOTHING;

-- 2. Create Products Table
CREATE TABLE IF NOT EXISTS public."Product" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    "categoryId" INTEGER REFERENCES public."Category"(id),
    "categoryName" TEXT,
    price NUMERIC NOT NULL,
    "quantityAvailable" INTEGER NOT NULL,
    "sellerId" INTEGER,
    "sellerName" TEXT,
    "productionType" TEXT,
    "imageUrl" TEXT,
    "farmerId" INTEGER,
    "farmerName" TEXT,
    category TEXT,
    rating NUMERIC DEFAULT 0,
    reviews INTEGER DEFAULT 0,
    "inStock" BOOLEAN DEFAULT true,
    unit TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Orders Table
CREATE TABLE IF NOT EXISTS public."Order" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "buyerId" INTEGER,
    "buyerName" TEXT,
    "totalAmount" NUMERIC NOT NULL,
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Shipped', 'Delivered', 'Cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: Ensure that PostgREST RLS (Row Level Security) policies are enabled on these tables or disable them for local testing.
